name: Continuous Integration

on: push

jobs:
  pipeline:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v1
        
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Pack
        run: dotnet pack --configuration Release --no-build
      
      - name: Push package to nuget
        run: dotnet nuget push Bleak\bin\Release\*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "${{secrets.NUGET_API_KEY}}"
